os: osx

branches:
  only:
    - master

install:
  - cmake --version

  - git clone --depth=1 --quiet -- https://github.com/julianstorer/JUCE.git ../JUCE

  - mkdir ~/SDKs
  - curl --location --output ~/SDKs/vstsdk3.zip http://www.steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip
  - unzip -q ~/SDKs/vstsdk3.zip -d ~/SDKs

script:
  - mkdir "examples/audio plugin host/build"
  - cd "examples/audio plugin host/build"
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .

  - cd $TRAVIS_BUILD_DIR

  - mkdir examples/NetworkGraphicsDemo/build
  - cd examples/NetworkGraphicsDemo/build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .

  - cd $TRAVIS_BUILD_DIR

  - mkdir extras/Projucer/build
  - cd extras/Projucer/build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .

  - cd $TRAVIS_BUILD_DIR

  - mkdir "examples/audio plugin demo/build"
  - cd "examples/audio plugin demo/build"
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
